<a href="https://colab.research.google.com/github/JesseHenson/School/blob/main/Mod5_CT1_opt1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/JesseHenson/School/main/data%20science%20vocab.csv",header=None)
df.columns = ['vocab','def','not']
df.head()

                         vocab  ...  not
0                    ACID Test  ...  NaN
1                  Aggregation  ...  NaN
2                    Algorithm  ...  NaN
3                   Alpha Risk  ...  NaN
4  Alternative Hypothesis (Ha)  ...  NaN

[5 rows x 3 columns]

In [ ]:
!pip install pydictionary

In [ ]:
from PyDictionary import PyDictionary

dictionary = PyDictionary()

def get_synonym(element):
  return dictionary.synonym(f'"{element}"')

df['synomnym'] = df.vocab.apply(get_synonym)

In [16]:
dictionary.synonym("good")

good has no Synonyms in the API

In [18]:
from nltk.corpus import wordnet
import nltk
nltk.download('wordnet')

dog = wordnet.synset('dog.n.01')
print(dog.lemma_names())

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
['dog', 'domestic_dog', 'Canis_familiaris']

In [38]:
def get_synonym(element):
  wordnet_words = wordnet.synsets(element)
  # print(wordnet_words)
  if wordnet_words != []:
    return wordnet_words[0].lemmas()[0].name()
  else: 
    return 

df['synomnym'] = df.vocab.apply(get_synonym)

In [39]:
df.head()

                         vocab  ...    synomnym
0                    ACID Test  ...        None
1                  Aggregation  ...  collection
2                    Algorithm  ...   algorithm
3                   Alpha Risk  ...        None
4  Alternative Hypothesis (Ha)  ...        None

[5 rows x 4 columns]

In [41]:
df.synomnym.isnull().sum()

121

In [42]:
df.describe()

         vocab  ...    synomnym
count      157  ...          36
unique     153  ...          32
top     Sample  ...  population
freq         3  ...           3

[4 rows x 4 columns]

In [54]:
import random

def remove_random_word(element):
  word_arr = element.split()
  # print(len(word_arr))
  if len(word_arr) > 5:
    remove_arr = np.random.choice(word_arr, 3, replace=False) 
    for word in remove_arr:
      word_arr.remove(word)
  # print(len(word_arr))
  return " ".join(word_arr)

df['def_augment'] = df['def'].apply(remove_random_word)
df.head()

                         vocab  ...                                        def_augment
0                    ACID Test  ...  A test to for atomicity, isolation and durabil...
1                  Aggregation  ...                    process of searching, and data.
2                    Algorithm  ...  A mathematical formula or process used perform...
3                   Alpha Risk  ...  The of making a Type I error. This probability...
4  Alternative Hypothesis (Ha)  ...  of a change or assumed to be true if the null ...

[5 rows x 5 columns]

In [55]:
df.to_csv("augmented_data.csv")